# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  vapoursynth-eedi3 = {
    pname = "vapoursynth-eedi3";
    version = "r4";
    src = fetchgit {
      url = "https://github.com/HomeOfVapourSynthEvolution/VapourSynth-EEDI3";
      rev = "r4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1q79l27arcfl7k49czsspb4z7zfr616xsxsb04x9b4d9l763716x";
    };
  };
}
