# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  vapoursynth-bwdif = {
    pname = "vapoursynth-bwdif";
    version = "r3";
    src = fetchgit {
      url = "https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Bwdif";
      rev = "r3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0xzsvs7xvb0na12dgc5sj2f3p4lrcs44ck1l086zzhy80kz6z0li";
    };
  };
  vapoursynth-eedi3 = {
    pname = "vapoursynth-eedi3";
    version = "r4";
    src = fetchgit {
      url = "https://github.com/HomeOfVapourSynthEvolution/VapourSynth-EEDI3";
      rev = "r4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1q79l27arcfl7k49czsspb4z7zfr616xsxsb04x9b4d9l763716x";
    };
  };
  vapoursynth-nnedi3 = {
    pname = "vapoursynth-nnedi3";
    version = "v12";
    src = fetchgit {
      url = "https://github.com/dubhater/vapoursynth-nnedi3";
      rev = "v12";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1valcf8ns4wrfq6q5js029a93i58vr37mqw5na6922avg04wzpwd";
    };
  };
}
